name: "DEPLOY HOM"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: "hom"
      aws-assume-role-arn: "123"
