name: "PROD DEPLOY"

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Check secrets
        run: echo "${{ secrets.AWS_ASSUME_ROLE_ARN_PROD }}"
